name = "cf-blog-discord-worker"
main = "index.js"
account_id = "0cee8561e3989abcad569632b8652767"
workers_dev = true
compatibility_date = "2021-10-04"

kv_namespaces = [
    { binding = "KV", id = "a9216137f5454043833781f64f0d277d" }
]

[triggers]
crons = ["* * * * *"]

[observability]
enabled = true
head_sampling_rate = 1

[[previews.kv_namespaces]]
binding = "KV"
id = "a9216137f5454043833781f64f0d277d"